### ISSUE TITLE
Any plans on updating this theme so users can set how many blog posts are on one page?

### ISSUE THREAD

**Issue by SJCaldwell** [victorvoid/space-jekyll-template#1]
For example, setting this options to "5" when you have 20 posts would result in four pages of posts to go through.

**Comment by ryukinix** [comment]
This is a very great idea, @SJCaldwell. I would like too.

**Comment by victorvoid** [comment]
@ryukinix @SJCaldwell  I was wondering of creating as well as a spacemacs with NeoTree, what do you think? It would be much like Spacemacs.
Click on the item, opened the post, so we would not be need to have a pagination =) 

![neotree](https://cloud.githubusercontent.com/assets/6734111/18859187/cff2fb68-843f-11e6-800f-558e7488387e.png)

**Comment by ryukinix** [comment]
this is really a good idea
