### ISSUE TITLE
Changing profile picture

### ISSUE THREAD

**Issue by kiwipop** [victorvoid/space-jekyll-template#14]
Can't seem to change profile picture anywhere? Is this an issue or is there something that I just happen to be missing? Nothing inside of the _config and I did some snooping around and seems it's through a link. Yet I can't seem to find where I can edit that

**Comment by victorvoid** [comment]
You can to change the profile picture on src [here](https://github.com/victorvoid/space-jekyll-template/blob/master/_includes/header-default.html#L5) :grimacing: But you're right, I'll configure it so you can put the picture link in the _config. Thanks. :thumbsup:

**Comment by victorvoid** [comment]
Ok, now you can change the profile picture in [_config.yml](https://github.com/victorvoid/space-jekyll-template/blob/master/_config.yml#L14).

**Comment by kiwipop** [comment]
Alright, thanks a lot!
