### ISSUE TITLE
Broken links on jekyllthemes.org

### ISSUE THREAD

**Issue by crichID** [victorvoid/space-jekyll-template#15]
FYI - I was looking at themes on jekyllthemes.org and noticed your homepage and demo links are both failing. 

The homepage is pointing to: `http://victor.github.io/space-jekyll-template/` instead of `https://victorvoid.github.io/space-jekyll-template/` and your demo is pointing to the same.

**Comment by victorvoid** [comment]
I don't know why it's so. However really, I had sent with the wrong link, but had already sent a pull request with the right link, but continued the old link in jekyllthemes.org, I [reported](https://github.com/mattvh/jekyllthemes/pull/380) the jekyllthemes.org, thank you very much for letting me know.

**Comment by JohannesMP** [comment]
Still broken :/

**Comment by victorvoid** [comment]
fixed :+1:
