### ISSUE TITLE
css preprocessor? 

### ISSUE THREAD

**Issue by jankrix** [victorvoid/space-jekyll-template#24]
Hi, what's your css preprocessor? is it stylus? I happen to be able to editing your theme styling in main.css but since _site is ignored nothing is pushed to my github pages, then I realize that I might editing the wrong files, turn out you have this .styl file extension.

note: I'm not familiar with .styl at all so I do my homework to install stylus, then grunt, then grunt-contrib-stylus but it seems I'm getting lost.
note 2: I'm not complaining since I can simply decide not to use your theme at all, but I think to explain how to workaround your theme is useful for beginners, unless beginners are not your target user at all

**Comment by victorvoid** [comment]
No problem @jankrix, thanks for you feedback, I'll help you, I've created two [sections](https://github.com/victorvoid/space-jekyll-template/blob/master/README.md#user-content-frontend-technologies) describing how you can run the theme on your machine. See if she will help you, and give me a feedback please.

**Comment by jankrix** [comment]
very much appreciate the added information victor, kudos

**Comment by jankrix** [comment]
everything works great victor, your latest updates to readme gives much clearer installation process, however github is now unable to load on my post despite I've already put my disqus username on the _config.yml.

I tried to register my domain on disqus (i'm using custom domain bought from namecheap) but it still not working
