### ISSUE TITLE
yarn.lock file

### ISSUE THREAD

**Issue by henriquenj** [victorvoid/space-jekyll-template#25]
Hello. 

First of all thanks for providing this template, it's really handy for people like me that do not have much experience in web development.

I was taking a look at the source tree, changing some details to suit my tastes and trying to understand how each tool was interacting with one another. I noticed there's the `package.json` with is read by `npm install` command and a `yarn.lock` which seems to be used by another dependency manager. Should I keep this file? What is the purpose of it? I don't see yarn being used anywhere in the template.

Thanks again for providing the template.

**Comment by victorvoid** [comment]
No problem! This project is not using npm to install the dependecies, it's using the [Yarn](https://yarnpkg.com/en), and you can use:

```bash
yarn install
```
Yarn is only a new CLI client that fetches modules from the npm registry. It's a new JavaScript package manager built by Facebook, Google, Exponent and Tilde. As can be read in the [official announcement](https://code.facebook.com/posts/1840075619545360), its purpose is to solve a handful of problems that these teams faced with npm, namely:

- installing packages wasn’t fast/consistent enough, and
- there were security concerns, as npm allows packages to run code on installation.

Read more about:
[Announcing yarn 1.0](https://code.facebook.com/posts/274518539716230/announcing-yarn-1-0/)

**Comment by victorvoid** [comment]
But you can use the npm to install the dependencies, and ignore the yarn.lock.

**Comment by henriquenj** [comment]
Thanks for the explanation. I read the documentation of yarn but didn't find anything about it on the template documentation, so I assumed `yarn.lock ` was uploaded by mistake. But if yarn and npm are complementary to each other, there's no issue to be solved. So I'll be closing this.
