### ISSUE TITLE
How do I add a new font and change its color?

### ISSUE THREAD

**Issue by deomorxsy** [victorvoid/space-jekyll-template#34]
Yo! I'm new on Jekyll and in the world of web design... so even reading the README.md i can't understand how do I change the font and the color in this theme (I mean the appearance of the text in posts). I tried to edit the file in the path assets/css/main.css and run Jekyll Serve to view the result, but can't understand too. Help me plz...

**Comment by victorvoid** [comment]
[This folder](https://github.com/victorvoid/space-jekyll-template/tree/master/src/styl) you can change all styles from page, there is a file called `_typo.styl` that you can change font, but after you change, you need to compile it files with [gulp](https://gulpjs.com/) to generate a `main.css`.

How to compile?

1. `npm install`
2. `gulp`

**Comment by deomorxsy** [comment]
Opa, valeu por responder; vi no seu perfil que você é brasileiro... se importa se eu mandar em pt-br?
Bom, basicamente o que aconteceu foi que meu gulp estava atualizado com o npm install, então começou a dar alguns erros no código pra compilar o Stylus. Então realizei o downgrade e ele está nas versões 'CLI version 2.0.1' e 'Local version 3.8.11', desse jeito consegui fazer rodar o Gulp com o script.
Então antes de você responder, eu já tinha editado o arquivo '/src/styl/_variables.styl' pra mudar o tema, e o que aconteceu dessa vez continua acontecendo agora.
Basicamente o que acontece é que o GULP roda, e aparece a mensagem do Stylus mudando o main.css, o servidor criado pelo gulp mostra a alteração, mas quando eu upo os arquivos para meu github, a atualização nas cores do tema não se mantém; é como se as atualizações que eu fiz fossem desfeitas:
![2018-10-31-205538_1366x768_scrot](https://user-images.githubusercontent.com/32879431/47825499-11788280-dd51-11e8-9ce5-bb7503543a4d.png)
![2018-10-31-210839_1366x768_scrot](https://user-images.githubusercontent.com/32879431/47825518-2d7c2400-dd51-11e8-89ac-350fb4515484.png)

Queria saber se você sabe como resolver isso, se é um bug ou eu tô errando em uma questão bem besta... desculpa pelo tamanho do texto, agradeço desde já! =D
