### ISSUE TITLE
Ligature Spacing in site-title CSS

### ISSUE THREAD

**Issue by thenickfish** [victorvoid/space-jekyll-template#36]
First, huge thanks for this amazing template! This is the coolest Jekyll template I've ever seen.

Ligatures are not being considered in the site-title class, which causes weird behavior in words containing a ligature. To reproduce this issue, you can set the site.username to 'office' in _config.yml.

This screenshot is from Chrome 69.0.3497.100 on macOS 10.13.6
<img width="394" alt="screen shot 2018-09-23 at 1 31 59 pm" src="https://user-images.githubusercontent.com/6274282/45932134-22093200-bf35-11e8-9997-954c466b4794.png">

**Comment by victorvoid** [comment]
@thenickfish thanks so much! 😸
