### ISSUE TITLE
ERROR `/assets/img/icons/favicon.ico' not found.

### ISSUE THREAD

**Issue by xuuexu** [victorvoid/space-jekyll-template#41]
https://github.com/victorvoid/space-jekyll-template/blob/8e76fc8a172a474b87d08b7c6714be92dce63dd1/_includes/head.html#L42

thanks for awesome template, but sometimes it pops up this error in command-line.

`ERROR  /assets/img/icons/favicon.ico not found.`

code provided above maybe help :)

I didn't find this file in master repo, did it mean favicon.ico should be added by user himself?

**Comment by victorvoid** [comment]
Hi @xuuexu, Yes, the idea is that user add favicon.ico

**Comment by xuuexu** [comment]
thanks for reply 😄
