### ISSUE TITLE
Non-minified main.js

### ISSUE THREAD

**Issue by Kajisav** [victorvoid/space-jekyll-template#5]
Thanks for making this theme available. I'm trying to learn how to theme Jekyll properly by looking over how you did this. Do you have a non-minified source of [/assets/js/main.js](https://github.com/victorvoid/space-jekyll-template/blob/master/assets/js/main.js)? I'm trying to figure out what parts of the javascript I need and what I don't and what all does what. Thanks in advance!

**Comment by victorvoid** [comment]
Thanks! All files needed for you change js/css/img (non-minified) are [here](https://github.com/victorvoid/space-jekyll-template/tree/master/src) and are compiled/minified for assets/

Install all dependencies with:
```npm install``` 

and run:
```gulp``` on terminal.

 =)
